import { CropRecord } from './recommendation-engine'

export interface FertilizerRuleRecord {
  id: string
  cropId: string
  cropName: string
  soilNStatus: string
  soilPStatus: string
  soilKStatus: string
  nitrogenPerAcre: number
  phosphorusPerAcre: number
  potassiumPerAcre: number
  sulphurPerAcre: number
  applicationStage: string
  source: string
  version: string
}

export const DEFAULT_CROPS: CropRecord[] = [
  {
    id: 'crop-paddy-rice',
    name: 'Paddy (Rice)',
    nameHi: 'धान',
    nameOr: 'ଧାନ',
    category: 'cereals',
    season: 'kharif',
    phMin: 5.5,
    phMax: 6.5,
    tempMin: 20,
    tempMax: 38,
    rainfallMin: 150,
    rainfallMax: 250,
    irrigationNeeded: true,
    duration: 120,
    waterRequirement: 'high',
    description: 'Paddy is the primary Kharif crop of India, especially in eastern states like Odisha, West Bengal, and Bihar.',
    descriptionHi: 'धान भारत की प्रमुख खरीफ फसल है।',
    descriptionOr: 'ଧାନ ଭାରତର ମୁଖ୍ୟ ଖରିଫ ଫସଲ।',
    scientificName: 'Oryza sativa',
  },
  {
    id: 'crop-wheat',
    name: 'Wheat',
    nameHi: 'गेहूं',
    nameOr: 'ଗହମ',
    category: 'cereals',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 10,
    tempMax: 25,
    rainfallMin: 40,
    rainfallMax: 100,
    irrigationNeeded: true,
    duration: 120,
    waterRequirement: 'medium',
    description: 'Wheat is a primary Rabi cereal grown widely across northern and central India.',
    descriptionHi: 'गेहूं उत्तर भारत की प्रमुख रबी फसल है।',
    descriptionOr: 'ଗହମ ଉତ୍ତର ଭାରତର ମୁଖ୍ୟ ରବି ଫସଲ।',
    scientificName: 'Triticum aestivum',
  },
  {
    id: 'crop-maize',
    name: 'Maize',
    nameHi: 'मक्का',
    nameOr: 'ମକା',
    category: 'cereals',
    season: 'kharif,rabi',
    phMin: 5.8,
    phMax: 7.5,
    tempMin: 18,
    tempMax: 35,
    rainfallMin: 60,
    rainfallMax: 110,
    irrigationNeeded: false,
    duration: 90,
    waterRequirement: 'medium',
    description: 'Maize is a versatile crop grown across seasons. It is used as food, fodder, and for poultry feed.',
    descriptionHi: 'मक्का एक बहुउपयोगी फसल है।',
    descriptionOr: 'ମକା ଏକ ବହୁ ଉପଯୋଗୀ ଫସଲ।',
    scientificName: 'Zea mays',
  },
  {
    id: 'crop-arhar-tur-pigeon-pea',
    name: 'Arhar (Tur/Pigeon Pea)',
    nameHi: 'अरहर/तुअर',
    nameOr: 'ହରଡ',
    category: 'pulses',
    season: 'kharif',
    phMin: 6.0,
    phMax: 7.0,
    tempMin: 20,
    tempMax: 35,
    rainfallMin: 60,
    rainfallMax: 150,
    irrigationNeeded: false,
    duration: 150,
    waterRequirement: 'low',
    description: 'Arhar (Tur dal) is a major protein-rich pulse crop that fixes atmospheric nitrogen.',
    descriptionHi: 'अरहर एक प्रमुख दलहनी फसल है जो मिट्टी को उपजाऊ बनाती है।',
    descriptionOr: 'ହରଡ ଏକ ମୁଖ୍ୟ ଡାଲି ଫସଲ।',
    scientificName: 'Cajanus cajan',
  },
  {
    id: 'crop-moong-green-gram',
    name: 'Moong (Green Gram)',
    nameHi: 'मूंग',
    nameOr: 'ମୁଗ',
    category: 'pulses',
    season: 'kharif,zaid',
    phMin: 6.2,
    phMax: 7.2,
    tempMin: 25,
    tempMax: 38,
    rainfallMin: 60,
    rainfallMax: 90,
    irrigationNeeded: false,
    duration: 65,
    waterRequirement: 'low',
    description: 'Short duration pulse crop, excellent for catch cropping and improving soil fertility.',
    descriptionHi: 'कम अवधि की दलहनी फसल, मिट्टी के स्वास्थ्य के लिए उत्तम।',
    descriptionOr: 'ଅଳ୍ପ ଦିନର ଡାଲି ଫସଲ, ମାଟି ପାଇଁ ଲାଭଦାୟକ।',
    scientificName: 'Vigna radiata',
  },
  {
    id: 'crop-groundnut',
    name: 'Groundnut',
    nameHi: 'मूंगफली',
    nameOr: 'ଚିନାବାଦାମ',
    category: 'oilseeds',
    season: 'kharif,rabi',
    phMin: 6.0,
    phMax: 7.0,
    tempMin: 22,
    tempMax: 35,
    rainfallMin: 50,
    rainfallMax: 100,
    irrigationNeeded: false,
    duration: 110,
    waterRequirement: 'medium',
    description: 'Major oilseed and food crop well suited to sandy loam soils.',
    descriptionHi: 'प्रमुख तिलहन फसल, रेतीली दोमट मिट्टी के लिए अनुकूल।',
    descriptionOr: 'ମୁଖ୍ୟ ତୈଳବୀଜ ଫସଲ, ବାଲିଆ ଦୋରସା ମାଟି ପାଇଁ ଉପଯୁକ୍ତ।',
    scientificName: 'Arachis hypogaea',
  },
  {
    id: 'crop-mustard',
    name: 'Mustard',
    nameHi: 'सरसों',
    nameOr: 'ସୋରିଷ',
    category: 'oilseeds',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 10,
    tempMax: 25,
    rainfallMin: 35,
    rainfallMax: 80,
    irrigationNeeded: false,
    duration: 110,
    waterRequirement: 'low',
    description: 'Mustard is the premier Rabi oilseed of India with high market demand.',
    descriptionHi: 'सरसों भारत की प्रमुख रबी तिलहन फसल है।',
    descriptionOr: 'ସୋରିଷ ଭାରତର ପ୍ରଧାନ ରବି ତୈଳ ଫସଲ।',
    scientificName: 'Brassica juncea',
  },
  {
    id: 'crop-tomato',
    name: 'Tomato',
    nameHi: 'टमाटर',
    nameOr: 'ବିଲାତି ବାଇଗଣ',
    category: 'vegetables',
    season: 'rabi,kharif',
    phMin: 6.0,
    phMax: 7.0,
    tempMin: 18,
    tempMax: 30,
    rainfallMin: 60,
    rainfallMax: 150,
    irrigationNeeded: true,
    duration: 90,
    waterRequirement: 'medium',
    description: 'High-value cash vegetable crop with high yield potential and strong local markets.',
    descriptionHi: 'टमाटर एक प्रमुख व्यावसायिक सब्जी फसल है।',
    descriptionOr: 'ବିଲାତି ବାଇଗଣ ଏକ ଲାଭଜନକ ପନିପରିବା।',
    scientificName: 'Solanum lycopersicum',
  },
  {
    id: 'crop-potato',
    name: 'Potato',
    nameHi: 'आलू',
    nameOr: 'ଆଳୁ',
    category: 'vegetables',
    season: 'rabi',
    phMin: 5.2,
    phMax: 6.5,
    tempMin: 15,
    tempMax: 25,
    rainfallMin: 50,
    rainfallMax: 100,
    irrigationNeeded: true,
    duration: 90,
    waterRequirement: 'medium',
    description: 'Potato requires cool climate during tuberization and well-drained fertile loose soil.',
    descriptionHi: 'आलू को कंद बनते समय ठंडे मौसम की आवश्यकता होती है।',
    descriptionOr: 'ଆଳୁ ଏକ ମୁଖ୍ୟ ପନିପରିବା ଫସଲ।',
    scientificName: 'Solanum tuberosum',
  },
  {
    id: 'crop-cotton',
    name: 'Cotton',
    nameHi: 'कपास',
    nameOr: 'ତୁଳା',
    category: 'oilseeds',
    season: 'kharif',
    phMin: 6.0,
    phMax: 8.0,
    tempMin: 22,
    tempMax: 40,
    rainfallMin: 60,
    rainfallMax: 150,
    irrigationNeeded: false,
    duration: 160,
    waterRequirement: 'medium',
    description: 'Cotton is a major commercial crop well adapted to deep black soils and warm climate.',
    descriptionHi: 'कपास एक प्रमुख व्यावसायिक फसल है।',
    descriptionOr: 'ତୁଳା ଏକ ଗୁରୁତ୍ୱପୂର୍ଣ ବ୍ୟବସାୟିକ ଫସଲ।',
    scientificName: 'Gossypium hirsutum',
  },
  {
    id: 'crop-chickpea',
    name: 'Chickpea / Gram',
    nameHi: 'चना',
    nameOr: 'ବୁଟ',
    category: 'pulses',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.8,
    tempMin: 14,
    tempMax: 28,
    rainfallMin: 40,
    rainfallMax: 90,
    irrigationNeeded: false,
    duration: 100,
    waterRequirement: 'low',
    description: 'Premier Rabi pulse crop with high protein content and drought tolerance.',
    descriptionHi: 'चना प्रमुख रबी दलहन है जो कम पानी में भी अच्छी पैदावार देता है।',
    descriptionOr: 'ବୁଟ ଏକ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ରବି ଡାଲି ଫସଲ।',
    scientificName: 'Cicer arietinum',
  },
  {
    id: 'crop-black-gram',
    name: 'Black Gram (Urad)',
    nameHi: 'उड़द',
    nameOr: 'ବିରି',
    category: 'pulses',
    season: 'kharif,zaid',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 25,
    tempMax: 40,
    rainfallMin: 60,
    rainfallMax: 100,
    irrigationNeeded: false,
    duration: 70,
    waterRequirement: 'low',
    description: 'Black gram is an important pulse crop adapted to warm humid conditions.',
    descriptionHi: 'उड़द एक महत्वपूर्ण दलहन फसल है।',
    descriptionOr: 'ବିରି ଏକ ଗୁରୁତ୍ୱପୂର୍ଣ ଡାଲ ଫସଲ।',
    scientificName: 'Vigna mungo',
  }
]

export const DEFAULT_FERTILIZER_RULES: Record<string, FertilizerRuleRecord> = {
  'paddy (rice)': {
    id: 'fr-paddy',
    cropId: 'crop-paddy-rice',
    cropName: 'Paddy (Rice)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 50,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 25,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/CRRI Recommendation 2023',
    version: '2023',
  },
  wheat: {
    id: 'fr-wheat',
    cropId: 'crop-wheat',
    cropName: 'Wheat',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 55,
    phosphorusPerAcre: 27,
    potassiumPerAcre: 20,
    sulphurPerAcre: 8,
    applicationStage: 'split',
    source: 'ICAR/IIWBR Recommendation 2023',
    version: '2023',
  },
  maize: {
    id: 'fr-maize',
    cropId: 'crop-maize',
    cropName: 'Maize',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 60,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 25,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/IIMR Recommendation 2023',
    version: '2023',
  },
  'chickpea / gram': {
    id: 'fr-chickpea',
    cropId: 'crop-chickpea',
    cropName: 'Chickpea / Gram',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 10,
    phosphorusPerAcre: 20,
    potassiumPerAcre: 10,
    sulphurPerAcre: 5,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Recommendation 2023',
    version: '2023',
  },
  'arhar (tur/pigeon pea)': {
    id: 'fr-arhar',
    cropId: 'crop-arhar-tur-pigeon-pea',
    cropName: 'Arhar (Tur/Pigeon Pea)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 10,
    phosphorusPerAcre: 20,
    potassiumPerAcre: 10,
    sulphurPerAcre: 5,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Recommendation 2023',
    version: '2023',
  },
  'moong (green gram)': {
    id: 'fr-moong',
    cropId: 'crop-moong-green-gram',
    cropName: 'Moong (Green Gram)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 8,
    phosphorusPerAcre: 16,
    potassiumPerAcre: 8,
    sulphurPerAcre: 4,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Recommendation 2023',
    version: '2023',
  },
  groundnut: {
    id: 'fr-groundnut',
    cropId: 'crop-groundnut',
    cropName: 'Groundnut',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 10,
    phosphorusPerAcre: 20,
    potassiumPerAcre: 20,
    sulphurPerAcre: 16,
    applicationStage: 'basal',
    source: 'ICAR/DGR Recommendation 2023',
    version: '2023',
  },
  mustard: {
    id: 'fr-mustard',
    cropId: 'crop-mustard',
    cropName: 'Mustard',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 40,
    phosphorusPerAcre: 20,
    potassiumPerAcre: 15,
    sulphurPerAcre: 20,
    applicationStage: 'split',
    source: 'ICAR/DRMR Recommendation 2023',
    version: '2023',
  },
  cotton: {
    id: 'fr-cotton',
    cropId: 'crop-cotton',
    cropName: 'Cotton',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 55,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 25,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/CICR Recommendation 2023',
    version: '2023',
  },
  tomato: {
    id: 'fr-tomato',
    cropId: 'crop-tomato',
    cropName: 'Tomato',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 50,
    phosphorusPerAcre: 30,
    potassiumPerAcre: 30,
    sulphurPerAcre: 8,
    applicationStage: 'split',
    source: 'State Dept. of Agriculture Recommendation',
    version: '2023',
  },
  potato: {
    id: 'fr-potato',
    cropId: 'crop-potato',
    cropName: 'Potato',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 60,
    phosphorusPerAcre: 30,
    potassiumPerAcre: 50,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/CPRI Recommendation 2023',
    version: '2023',
  }
}

export function getFallbackFertilizerRule(nameOrId: string) {
  const key = nameOrId.toLowerCase()
  for (const [k, v] of Object.entries(DEFAULT_FERTILIZER_RULES)) {
    if (key.includes(k) || k.includes(key)) {
      return v
    }
  }
  return DEFAULT_FERTILIZER_RULES['paddy (rice)']
}
