import { CropRecord } from './recommendation-engine'

export interface FertilizerRuleRecord {
  id: string
  cropId: string
  cropName: string
  soilNStatus: string
  soilPStatus: string
  soilKStatus: string
  nitrogenPerAcre: number
  phosphorusPerAcre: number
  potassiumPerAcre: number
  sulphurPerAcre: number
  applicationStage: string
  source: string
  version: string
}

export const DEFAULT_CROPS: CropRecord[] = [
  // --- CEREALS ---
  {
    id: 'crop-paddy-rice',
    name: 'Paddy (Rice)',
    nameHi: 'धान (चावल)',
    nameOr: 'ଧାନ (Rice)',
    category: 'cereals',
    season: 'kharif',
    phMin: 5.5,
    phMax: 6.8,
    tempMin: 20,
    tempMax: 38,
    rainfallMin: 140,
    rainfallMax: 280,
    irrigationNeeded: true,
    duration: 120,
    waterRequirement: 'high',
    description: 'Premier staple cereal crop of India, thrives in clayey to loamy soils with assured water.',
    descriptionHi: 'भारत की प्रमुख खरीफ फसल, पर्याप्त पानी और चिकनी-दोमट मिट्टी में उत्तम पैदावार देती है।',
    descriptionOr: 'ଭାରତର ମୁଖ୍ୟ ଖରିଫ ଫସଲ, ପର୍ଯ୍ୟାପ୍ତ ଜଳ ଓ ଦୋରସା ମାଟିରେ ଭଲ ଅମଳ ହୁଏ।',
    scientificName: 'Oryza sativa',
  },
  {
    id: 'crop-wheat',
    name: 'Wheat',
    nameHi: 'गेहूं',
    nameOr: 'ଗହମ',
    category: 'cereals',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 10,
    tempMax: 25,
    rainfallMin: 40,
    rainfallMax: 100,
    irrigationNeeded: true,
    duration: 120,
    waterRequirement: 'medium',
    description: 'Premier winter Rabi cereal grown extensively across Northern, Central, and Eastern plains.',
    descriptionHi: 'प्रमुख रबी खाद्यान्न फसल, ठंडे मौसम और अच्छी जल निकासी वाली दोमट मिट्टी में फलती-फूलती है।',
    descriptionOr: 'ପ୍ରମୁଖ ରବି ଖାଦ୍ୟ ଫସଲ, ଥଣ୍ଡା ପାଗ ଓ ନିଷ୍କାସିତ ଦୋରସା ମାଟିରେ ଉତ୍ତମ ହୁଏ।',
    scientificName: 'Triticum aestivum',
  },
  {
    id: 'crop-maize',
    name: 'Maize (Corn)',
    nameHi: 'मक्का',
    nameOr: 'ମକା',
    category: 'cereals',
    season: 'kharif,rabi',
    phMin: 5.8,
    phMax: 7.5,
    tempMin: 18,
    tempMax: 35,
    rainfallMin: 60,
    rainfallMax: 120,
    irrigationNeeded: false,
    duration: 95,
    waterRequirement: 'medium',
    description: 'Highly versatile multi-season cereal for food, poultry feed, and industrial starch.',
    descriptionHi: 'बहुमुखी बहु-मौसमी अनाज, अच्छी जल निकासी वाली उपजाऊ दोमट मिट्टी के अनुकूल।',
    descriptionOr: 'ଏକ ବହୁମୁଖୀ ଫସଲ, ଖାଦ୍ୟ ଓ କୁକୁଡ଼ା ଦାନା ପାଇଁ ବହୁତ ଚାହିଦା ଥାଏ।',
    scientificName: 'Zea mays',
  },

  // --- PULSES (LEGUMES - NITROGEN FIXING) ---
  {
    id: 'crop-chickpea',
    name: 'Chickpea (Chana / Gram)',
    nameHi: 'चना (छोला)',
    nameOr: 'ବୁଟ / ଚଣା',
    category: 'pulses',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.8,
    tempMin: 14,
    tempMax: 28,
    rainfallMin: 35,
    rainfallMax: 90,
    irrigationNeeded: false,
    duration: 100,
    waterRequirement: 'low',
    description: 'Premier high-protein Rabi pulse, fixes atmospheric nitrogen and thrives in residual moisture.',
    descriptionHi: 'प्रमुख रबी दलहनी फसल, वायुमंडलीय नाइट्रोजन स्थिर करती है और कम पानी में बेहतरीन उत्पादन देती है।',
    descriptionOr: 'ମୁଖ୍ୟ ରବି ଡାଲି ଫସଲ, ମାଟିରେ ଯବକ୍ଷାରଜାନ ସ୍ଥିର କରେ ଓ କମ ଜଳରେ ଭଲ ଅମଳ ଦିଏ।',
    scientificName: 'Cicer arietinum',
  },
  {
    id: 'crop-arhar-tur-pigeon-pea',
    name: 'Arhar (Tur / Pigeon Pea)',
    nameHi: 'अरहर (तुअर दाल)',
    nameOr: 'ହରଡ଼ ଡାଲି',
    category: 'pulses',
    season: 'kharif',
    phMin: 6.0,
    phMax: 7.2,
    tempMin: 20,
    tempMax: 36,
    rainfallMin: 60,
    rainfallMax: 150,
    irrigationNeeded: false,
    duration: 150,
    waterRequirement: 'low',
    description: 'Deep-rooted, drought-tolerant Kharif legume that enriches subsoil nutrient availability.',
    descriptionHi: 'गहरी जड़ों वाली सूखा-सहिष्णु दलहन फसल, मिट्टी की उर्वरता और नाइट्रोजन बढ़ाने में सहायक।',
    descriptionOr: 'ଗଭୀର ଚେର ଥିବା ଶୁଷ୍କ-ସହଣୀୟ ଡାଲି ଫସଲ, ମାଟିର ଉର୍ବରତା ବୃଦ୍ଧି କରେ।',
    scientificName: 'Cajanus cajan',
  },
  {
    id: 'crop-moong-green-gram',
    name: 'Moong (Green Gram)',
    nameHi: 'मूंग दाल',
    nameOr: 'ମୁଗ ଡାଲି',
    category: 'pulses',
    season: 'kharif,zaid',
    phMin: 6.2,
    phMax: 7.4,
    tempMin: 24,
    tempMax: 38,
    rainfallMin: 45,
    rainfallMax: 90,
    irrigationNeeded: false,
    duration: 65,
    waterRequirement: 'low',
    description: 'Short-duration catch pulse (60-65 days), ideal for crop rotation and Summer/Zaid cultivation.',
    descriptionHi: 'कम अवधि (60-65 दिन) की दलहन फसल, ग्रीष्मकालीन और जायद खेती के लिए उत्तम।',
    descriptionOr: 'ଅଳ୍ପ ଦିନିଆ (୬୦-୬୫ ଦିନ) ଡାଲି ଫସଲ, ଖରାଟିଆ ଓ ଫସଲ ପର୍ଯ୍ୟାୟ ପାଇଁ ଆଦର୍ଶ।',
    scientificName: 'Vigna radiata',
  },
  {
    id: 'crop-black-gram',
    name: 'Black Gram (Urad Dal)',
    nameHi: 'उड़द दाल',
    nameOr: 'ବିରି ଡାଲି',
    category: 'pulses',
    season: 'kharif,zaid',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 24,
    tempMax: 38,
    rainfallMin: 55,
    rainfallMax: 100,
    irrigationNeeded: false,
    duration: 75,
    waterRequirement: 'low',
    description: 'High-value protein pulse adapted to warm, humid tropical and sub-tropical conditions.',
    descriptionHi: 'उष्णकटिबंधीय मौसम के अनुकूल उच्च प्रोटीन वाली दलहनी फसल।',
    descriptionOr: 'ଉଷ୍ମ ଆର୍ଦ୍ର ପାଣିପାଗରେ ଚାଷ ଉପଯୋଗୀ ପୁଷ୍ଟିକର ଡାଲି ଫସଲ।',
    scientificName: 'Vigna mungo',
  },
  {
    id: 'crop-lentil',
    name: 'Lentil (Masoor Dal)',
    nameHi: 'मसूर दाल',
    nameOr: 'ମସୁର ଡାଲି',
    category: 'pulses',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.8,
    tempMin: 12,
    tempMax: 26,
    rainfallMin: 35,
    rainfallMax: 80,
    irrigationNeeded: false,
    duration: 105,
    waterRequirement: 'low',
    description: 'Hardy Rabi legume with low moisture requirement, suitable for relay and conservation tillage.',
    descriptionHi: 'कम नमी में उगने वाली रबी दलहन, उथली से मध्यम दोमट मिट्टी में सफल।',
    descriptionOr: 'କମ ପାଣି ଆବଶ୍ୟକ କରୁଥିବା ଶୀତକାଳୀନ ରବି ଡାଲି ଫସଲ।',
    scientificName: 'Lens culinaris',
  },

  // --- OILSEEDS ---
  {
    id: 'crop-mustard',
    name: 'Mustard (Sarson / Rai)',
    nameHi: 'सरसों / राई',
    nameOr: 'ସୋରିଷ',
    category: 'oilseeds',
    season: 'rabi',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 10,
    tempMax: 26,
    rainfallMin: 30,
    rainfallMax: 80,
    irrigationNeeded: false,
    duration: 110,
    waterRequirement: 'low',
    description: 'Premier winter oilseed crop of India with high oil content and low water requirement.',
    descriptionHi: 'भारत की प्रमुख रबी तिलहन फसल, कम पानी में अच्छी पैदावार और उच्च तेल की मात्रा देती है।',
    descriptionOr: 'ଭାରତର ପ୍ରମୁଖ ରବି ତୈଳବୀଜ ଫସଲ, କମ ପାଣିରେ ଉତ୍ତମ ଅମଳ ଦିଏ।',
    scientificName: 'Brassica juncea',
  },
  {
    id: 'crop-groundnut',
    name: 'Groundnut (Peanut)',
    nameHi: 'मूंगफली',
    nameOr: 'ଚିନାବାଦାମ',
    category: 'oilseeds',
    season: 'kharif,rabi',
    phMin: 6.0,
    phMax: 7.2,
    tempMin: 22,
    tempMax: 35,
    rainfallMin: 50,
    rainfallMax: 100,
    irrigationNeeded: false,
    duration: 115,
    waterRequirement: 'medium',
    description: 'Valuable cash-cum-oilseed crop, thrives best in well-drained sandy loam and red soils.',
    descriptionHi: 'बलुई दोमट और भुरभुरी मिट्टी के लिए अनुकूल प्रमुख तिलहन एवं नकदी फसल।',
    descriptionOr: 'ବାଲିଆ ଦୋରସା ଓ ନାଲି ମାଟି ପାଇଁ ଅତ୍ୟନ୍ତ ଉପଯୁକ୍ତ ଲାଭଜନକ ତୈଳ ଫସଲ।',
    scientificName: 'Arachis hypogaea',
  },
  {
    id: 'crop-soybean',
    name: 'Soybean',
    nameHi: 'सोयाबीन',
    nameOr: 'ସୋୟାବିନ',
    category: 'oilseeds',
    season: 'kharif',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 20,
    tempMax: 35,
    rainfallMin: 60,
    rainfallMax: 130,
    irrigationNeeded: false,
    duration: 95,
    waterRequirement: 'medium',
    description: 'Dual-purpose oilseed and protein crop, performs well in black cotton and fertile loam soils.',
    descriptionHi: 'काली व दोमट मिट्टी में भरपूर पैदावार देने वाली खरीफ की प्रमुख तिलहन फसल।',
    descriptionOr: 'କଳା ଓ ଦୋରସା ମାଟିରେ ଭଲ ଅମଳ ଦେଉଥିବା ଉଚ୍ଚ ପ୍ରୋଟିନଯୁକ୍ତ ଫସଲ।',
    scientificName: 'Glycine max',
  },
  {
    id: 'crop-sesame',
    name: 'Sesame (Til)',
    nameHi: 'तिल',
    nameOr: 'ରାଶି / ତିଳ',
    category: 'oilseeds',
    season: 'kharif,zaid',
    phMin: 5.8,
    phMax: 7.6,
    tempMin: 25,
    tempMax: 38,
    rainfallMin: 40,
    rainfallMax: 80,
    irrigationNeeded: false,
    duration: 85,
    waterRequirement: 'low',
    description: 'Extremely drought-tolerant oilseed, ideal for rainfed marginal lands and light soils.',
    descriptionHi: 'सूखा-सहिष्णु तिलहन फसल, हल्की और असिंचित जमीन के लिए सर्वोत्तम।',
    descriptionOr: 'ଶୁଷ୍କ ପରିସ୍ଥିତି ସହ୍ୟ କରୁଥିବା ତୈଳ ଫସଲ, କମ ପାଣିରେ ମଧ୍ୟ ଲାଭଜନକ।',
    scientificName: 'Sesamum indicum',
  },

  // --- VEGETABLES & HORTICULTURE ---
  {
    id: 'crop-tomato',
    name: 'Tomato',
    nameHi: 'टमाटर',
    nameOr: 'ବିଲାତି ବାଇଗଣ',
    category: 'vegetables',
    season: 'rabi,kharif',
    phMin: 6.0,
    phMax: 7.0,
    tempMin: 18,
    tempMax: 32,
    rainfallMin: 50,
    rainfallMax: 120,
    irrigationNeeded: true,
    duration: 90,
    waterRequirement: 'medium',
    description: 'High-value commercial vegetable with fast returns, excels under drip irrigation.',
    descriptionHi: 'उच्च मुनाफा देने वाली व्यावसायिक सब्जी फसल, ड्रिप सिंचाई में सर्वाधिक उपज देती है।',
    descriptionOr: 'ଅଧିକ ଲାଭ ଦେଉଥିବା ପନିପରିବା, ଡ୍ରିପ ଜଳସେଚନରେ ପ୍ରଚୁର ଅମଳ ଦିଏ।',
    scientificName: 'Solanum lycopersicum',
  },
  {
    id: 'crop-potato',
    name: 'Potato',
    nameHi: 'आलू',
    nameOr: 'ଆଳୁ',
    category: 'vegetables',
    season: 'rabi',
    phMin: 5.2,
    phMax: 6.5,
    tempMin: 14,
    tempMax: 24,
    rainfallMin: 40,
    rainfallMax: 90,
    irrigationNeeded: true,
    duration: 95,
    waterRequirement: 'medium',
    description: 'Premier cool-season tuber vegetable requiring loose, well-aerated sandy loam soil.',
    descriptionHi: 'ठंडे मौसम की मुख्य कंद फसल, भुरभुरी और उपजाऊ दोमट मिट्टी में भारी उत्पादन।',
    descriptionOr: 'ଶୀତଦିନିଆ ମୁଖ୍ୟ କନ୍ଦ ପନିପରିବା, ନରମ ଓ ବାଲିଆ ଦୋରସା ମାଟି ଆବଶ୍ୟକ କରେ।',
    scientificName: 'Solanum tuberosum',
  },
  {
    id: 'crop-onion',
    name: 'Onion',
    nameHi: 'प्याज',
    nameOr: 'ପିଆଜ',
    category: 'vegetables',
    season: 'rabi,kharif',
    phMin: 6.0,
    phMax: 7.2,
    tempMin: 16,
    tempMax: 30,
    rainfallMin: 45,
    rainfallMax: 90,
    irrigationNeeded: true,
    duration: 110,
    waterRequirement: 'medium',
    description: 'Major commercial bulb crop with high market liquidity, requires well-pulverized loam.',
    descriptionHi: 'बाजार में लगातार मांग वाली प्याज की खेती, अच्छी दोमट मिट्टी में अत्यधिक लाभकारी।',
    descriptionOr: 'ସବୁବେଳେ ବଜାର ଚାହିଦା ଥିବା ବ୍ୟବସାୟିକ ଫସଲ, ଉତ୍ତମ ଦୋରସା ମାଟି ଆବଶ୍ୟକ କରେ।',
    scientificName: 'Allium cepa',
  },
  {
    id: 'crop-okra',
    name: "Okra (Lady's Finger / Bhindi)",
    nameHi: 'भिंडी',
    nameOr: 'ଭେଣ୍ଡି',
    category: 'vegetables',
    season: 'kharif,zaid',
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 22,
    tempMax: 38,
    rainfallMin: 50,
    rainfallMax: 110,
    irrigationNeeded: true,
    duration: 70,
    waterRequirement: 'medium',
    description: 'Fast-yielding warm season vegetable producing continuous daily/weekly income.',
    descriptionHi: 'गर्म मौसम की लोकप्रिय सब्जी, दैनिक/साप्ताहिक आमदनी देने वाली लाभकारी फसल।',
    descriptionOr: 'ଖରାଟିଆ ଓ ବର୍ଷାଦିନିଆ ପନିପରିବା, ନିୟମିତ ସାପ୍ତାହିକ ରୋଜଗାର ପ୍ରଦାନ କରେ।',
    scientificName: 'Abelmoschus esculentus',
  },
  {
    id: 'crop-watermelon',
    name: 'Watermelon',
    nameHi: 'तरबूज',
    nameOr: 'ତରଭୁଜ',
    category: 'vegetables',
    season: 'zaid',
    phMin: 6.0,
    phMax: 7.2,
    tempMin: 24,
    tempMax: 38,
    rainfallMin: 30,
    rainfallMax: 70,
    irrigationNeeded: true,
    duration: 85,
    waterRequirement: 'medium',
    description: 'Premier Zaid/Summer fruit-vegetable, thrives in warm sunny conditions and riverbeds.',
    descriptionHi: 'गर्मियों (जायद) की अत्यधिक लाभकारी नकदी फसल, रेतीली-दोमट मिट्टी में शानदार उपज।',
    descriptionOr: 'ଖରାଦିନର ଉଚ୍ଚ ଲାଭଜନକ ଜାଏଦ ଫସଲ, ବାଲିଆ ମାଟି ଓ ଖରାରେ ପ୍ରଚୁର ଅମଳ ଦିଏ।',
    scientificName: 'Citrullus lanatus',
  },

  // --- COMMERCIAL & CASH CROPS ---
  {
    id: 'crop-cotton',
    name: 'Cotton (Kapas)',
    nameHi: 'कपास (सफेद सोना)',
    nameOr: 'ତୁଳା / କପା',
    category: 'oilseeds',
    season: 'kharif',
    phMin: 6.0,
    phMax: 8.0,
    tempMin: 22,
    tempMax: 40,
    rainfallMin: 60,
    rainfallMax: 130,
    irrigationNeeded: false,
    duration: 160,
    waterRequirement: 'medium',
    description: 'Major industrial fibre-cum-oil commercial crop, ideal for deep black and fertile soils.',
    descriptionHi: 'काली कपासी मिट्टी में उगाई जाने वाली प्रमुख औद्योगिक नकदी फसल।',
    descriptionOr: 'କଳା ଓ ଉର୍ବର ମାଟିରେ ଚାଷ କରାଯାଉଥିବା ପ୍ରମୁଖ ବ୍ୟବସାୟିକ ତନ୍ତୁ ଫସଲ।',
    scientificName: 'Gossypium hirsutum',
  },
  {
    id: 'crop-sugarcane',
    name: 'Sugarcane',
    nameHi: 'गन्ना',
    nameOr: 'ଆଖୁ',
    category: 'cereals',
    season: 'kharif,rabi',
    phMin: 6.0,
    phMax: 7.8,
    tempMin: 20,
    tempMax: 38,
    rainfallMin: 120,
    rainfallMax: 200,
    irrigationNeeded: true,
    duration: 330,
    waterRequirement: 'high',
    description: 'Long-duration cash crop with guaranteed mill procurement, demands continuous irrigation.',
    descriptionHi: 'दीर्घकालिक नकदी फसल, सुनिश्चित बाजार और प्रचुर सिंचाई सुविधा की आवश्यकता।',
    descriptionOr: 'ଦୀର୍ଘକାଳୀନ ଅର୍ଥକାରୀ ଫସଲ, ନିୟମିତ ଜଳସେଚନ ଓ ଉର୍ବର ମାଟି ଆବଶ୍ୟକ କରେ।',
    scientificName: 'Saccharum officinarum',
  },
  {
    id: 'crop-turmeric',
    name: 'Turmeric (Haldi)',
    nameHi: 'हल्दी',
    nameOr: 'ହଳଦୀ',
    category: 'vegetables',
    season: 'kharif',
    phMin: 5.5,
    phMax: 7.2,
    tempMin: 20,
    tempMax: 35,
    rainfallMin: 120,
    rainfallMax: 220,
    irrigationNeeded: false,
    duration: 240,
    waterRequirement: 'medium',
    description: 'High-value rhizome spice crop with strong export demand, excels in fertile red/loam soils.',
    descriptionHi: 'उच्च औषधीय और बाजार मूल्य वाली मसाला फसल, छायादार व नम जलवायु में उपयुक्त।',
    descriptionOr: 'ଉଚ୍ଚ ମୂଲ୍ୟଯୁକ୍ତ ମସଲା ଫସଲ, ଆର୍ଦ୍ର ଜଳବାୟୁ ଓ ଢିପ ଜମିରେ ଉତ୍କୃଷ୍ଟ ହୁଏ।',
    scientificName: 'Curcuma longa',
  }
]

export const DEFAULT_FERTILIZER_RULES: Record<string, FertilizerRuleRecord> = {
  'paddy (rice)': {
    id: 'fr-paddy',
    cropId: 'crop-paddy-rice',
    cropName: 'Paddy (Rice)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 50,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 25,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/CRRI Guidelines 2024',
    version: '2024',
  },
  wheat: {
    id: 'fr-wheat',
    cropId: 'crop-wheat',
    cropName: 'Wheat',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 55,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 20,
    sulphurPerAcre: 8,
    applicationStage: 'split',
    source: 'ICAR/IIWBR Guidelines 2024',
    version: '2024',
  },
  'maize (corn)': {
    id: 'fr-maize',
    cropId: 'crop-maize',
    cropName: 'Maize (Corn)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 55,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 25,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/IIMR Guidelines 2024',
    version: '2024',
  },
  'chickpea (chana / gram)': {
    id: 'fr-chickpea',
    cropId: 'crop-chickpea',
    cropName: 'Chickpea (Chana / Gram)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 10,
    phosphorusPerAcre: 20,
    potassiumPerAcre: 10,
    sulphurPerAcre: 8,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Guidelines 2024',
    version: '2024',
  },
  'arhar (tur / pigeon pea)': {
    id: 'fr-arhar',
    cropId: 'crop-arhar-tur-pigeon-pea',
    cropName: 'Arhar (Tur / Pigeon Pea)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 10,
    phosphorusPerAcre: 22,
    potassiumPerAcre: 10,
    sulphurPerAcre: 8,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Guidelines 2024',
    version: '2024',
  },
  'moong (green gram)': {
    id: 'fr-moong',
    cropId: 'crop-moong-green-gram',
    cropName: 'Moong (Green Gram)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 8,
    phosphorusPerAcre: 18,
    potassiumPerAcre: 8,
    sulphurPerAcre: 6,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Guidelines 2024',
    version: '2024',
  },
  'black gram (urad dal)': {
    id: 'fr-urad',
    cropId: 'crop-black-gram',
    cropName: 'Black Gram (Urad Dal)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 8,
    phosphorusPerAcre: 18,
    potassiumPerAcre: 8,
    sulphurPerAcre: 6,
    applicationStage: 'basal',
    source: 'ICAR/IIPR Guidelines 2024',
    version: '2024',
  },
  'mustard (sarson / rai)': {
    id: 'fr-mustard',
    cropId: 'crop-mustard',
    cropName: 'Mustard (Sarson / Rai)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 40,
    phosphorusPerAcre: 20,
    potassiumPerAcre: 15,
    sulphurPerAcre: 18,
    applicationStage: 'split',
    source: 'ICAR/DRMR Guidelines 2024',
    version: '2024',
  },
  'groundnut (peanut)': {
    id: 'fr-groundnut',
    cropId: 'crop-groundnut',
    cropName: 'Groundnut (Peanut)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 12,
    phosphorusPerAcre: 24,
    potassiumPerAcre: 20,
    sulphurPerAcre: 15,
    applicationStage: 'basal',
    source: 'ICAR/DGR Guidelines 2024',
    version: '2024',
  },
  tomato: {
    id: 'fr-tomato',
    cropId: 'crop-tomato',
    cropName: 'Tomato',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 50,
    phosphorusPerAcre: 30,
    potassiumPerAcre: 35,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'State Horticulture Dept. 2024',
    version: '2024',
  },
  potato: {
    id: 'fr-potato',
    cropId: 'crop-potato',
    cropName: 'Potato',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 60,
    phosphorusPerAcre: 30,
    potassiumPerAcre: 50,
    sulphurPerAcre: 12,
    applicationStage: 'split',
    source: 'ICAR/CPRI Guidelines 2024',
    version: '2024',
  },
  'cotton (kapas)': {
    id: 'fr-cotton',
    cropId: 'crop-cotton',
    cropName: 'Cotton (Kapas)',
    soilNStatus: 'medium',
    soilPStatus: 'medium',
    soilKStatus: 'medium',
    nitrogenPerAcre: 50,
    phosphorusPerAcre: 25,
    potassiumPerAcre: 25,
    sulphurPerAcre: 10,
    applicationStage: 'split',
    source: 'ICAR/CICR Guidelines 2024',
    version: '2024',
  }
}

export function getFallbackFertilizerRule(nameOrId: string): FertilizerRuleRecord {
  const key = nameOrId.toLowerCase()
  for (const [k, v] of Object.entries(DEFAULT_FERTILIZER_RULES)) {
    if (key.includes(k) || k.includes(key) || key.includes(v.cropName.toLowerCase())) {
      return v
    }
  }
  return DEFAULT_FERTILIZER_RULES['paddy (rice)']
}
